name: Check new links against deployment
# This workflow "triggers" and skips on deployment because GitHub Actions /
# Checks refuses to show the check on deployment_status
on:
  - deployment_status
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    if:
      github.event.deployment.ref != 'main' &&
      github.event.deployment_status.state == 'success'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Run Link Check
        id: check
        run: >-
          echo "::set-output
          report=Link Check Report\\n\\n$(npx
          repo-link-check
          -d
          -c config/link-check/config.yml
          -r ${{ github.event.deployment.payload.web_url }})"

      - name: Find Existing Link Check Report Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Link Check Report
  
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2
        if: always()
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Link Check Report
            ${{ steps.check.outputs.report }}
          edit-mode: replace
