name: Check new links against deployment
# This workflow "triggers" and skips on deployment because GitHub Actions /
# Checks refuses to show the check on deployment_status
on:
  - deployment_status
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    if:
      github.event.deployment.ref != 'main' &&
      github.event.deployment_status.state == 'success'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Run Link Check
        id: check
        run: 'yarn link-check-diff -r ${{ github.event.deployment.payload.web_url }}'
        uses: iterative/link-check.action@v0.12
